### ISSUE TITLE
How to get mac os-like fullscreen mode?

### ISSUE THREAD

**Issue by ghost** [supaboss/nobara-dotfiles#2]
Hey again! I've been using your customization for a while and I really enjoy it. But I have one question. I saw on screenshot that application windows hasn't completely fullscreened windows, whether it Spotify or Firefox. It looks like in Mac os and pairs very nice with this rounded bar on top. But I don't have it on my system. How can I get this cool little future?

**Comment by slashedzer0** [comment]
I kinda understand your point. did you install the [Pop Shell](https://github.com/pop-os/shell) extension? if so, make sure it's working properly as well,

in some cases, Pop Shell has compatibility issues with several distros -- which is why I use the official Nobara variant that comes pre-installed with it.

**Comment by ghost** [comment]
Oh, yes, it's working now. I just had this extension turned off. Looks brilliant now, sorry for this stupid request btw :) I'm very newbie in this system but my user experience is so enjoyable because of people like you, thanks!
